### ISSUE TITLE
Enterring rubik's cube state manually from physical cube

### ISSUE THREAD

**Issue by denizsincar29** [kyo-takano/EfficientCube#1]
Hello. I was experimenting with the efficient cube package and wanted to enter rubic's cube colors manually reading from my own cube. How would I go for it?
What is the order in each face to enter the colors into the 54 length array and what is the face order?
I think i got it right,but:
upper face: from left to right rows than from back towards you columns.
lower face (if not turned the cube): opposit direction, starting from closest to you on the right corner, going left, than second row is more forwards.
Not sure how left and right face is positioned.
Front face, i think, is ordered again from up left, going right, and columns go down. And back one goes opposit, right?
Can you tell me how to position my physical rubics cube and enter colors into the numpy array?
Thank you!

**Comment by kyo-takano** [comment]
@denizsincar29, thank you for trying out EfficientCube.

For the representation scheme, please take a look at the following docstring in the source code:
https://github.com/kyo-takano/efficientcube/blob/976d02b0de3a7cdf3fc7a4f9d80e082f65eafbd5/efficientcube/environments.py#L147-L175

This should provide the necessary information to your question.

**Comment by denizsincar29** [comment]
@kyo-takano I couldn't read the docstring properly because my screenreader tells me just a bunch of numbers, e.g. 3 numbers in 3 first lines, than 12 numbers...
